table DimDate
	lineageTag: 58a4c420-761e-482e-9820-a86fed71c47a

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 9a27662a-9880-4742-b18c-c239fef31eb2
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: int64
		formatString: 0
		lineageTag: fe21edec-1122-41f0-97f4-083fa77f7a00
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 4e7be87c-7124-44ad-9d6c-cccc2c66001c
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 9c12be62-30f0-4a84-87f9-d85c5d1470cb
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column MonthNum
		dataType: int64
		formatString: 0
		lineageTag: a7858541-1c2b-47ad-b693-e65cfc07f1d2
		summarizeBy: none
		sourceColumn: MonthNum

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: f1ec8f59-f99b-410b-8447-94e146dd23e1
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: MonthNum

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column WeekNum
		dataType: int64
		formatString: 0
		lineageTag: d8430dc9-9afb-471c-9191-281d84aef790
		summarizeBy: none
		sourceColumn: WeekNum

		annotation SummarizationSetBy = Automatic

	column DayNum
		dataType: int64
		formatString: 0
		lineageTag: a8c31e50-4bb9-4ff9-8100-00b75fd41547
		summarizeBy: none
		sourceColumn: DayNum

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 33a7d1b4-65dc-4242-bb86-0a0d821370b1
		summarizeBy: none
		sourceColumn: DayName

		annotation SummarizationSetBy = Automatic

	column IsWeekend
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: bf10d991-baa9-46a0-bf43-2783abf71376
		summarizeBy: none
		sourceColumn: IsWeekend

		annotation SummarizationSetBy = Automatic

	partition DimDate = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\KiranCherukupally\OneDrive - EPAM\My Data\KnowYourBI\Projects\MLRITM\Projects\IGNITE-2\22 - Operation Theater Efficiency & Utilization Analytics\files\OT_DimDate.xlsx"), null, true),
				    DimDate_Sheet = Source{[Item="DimDate",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(DimDate_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DateKey", Int64.Type}, {"Date", Int64.Type}, {"Year", Int64.Type}, {"Quarter", type text}, {"MonthNum", Int64.Type}, {"MonthName", type text}, {"WeekNum", Int64.Type}, {"DayNum", Int64.Type}, {"DayName", type text}, {"IsWeekend", type logical}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

